### ISSUE TITLE
Localize date

### ISSUE THREAD

**Issue by aloisdg** [davide-ravasi/memolist#155]
Hello,

You may want to rely on the builtin formatter instead of doing your own in [dateConverter.js](
https://github.com/davide-ravasi/memolist/blob/master/src/outils/dateConverter.js). Right now you are using short English month with the not so English format DD MMM YYYY. As a french person writing in English, I totally see why though. Well.

Moving from:

```js
export const convertDateFromTimestamp = ({seconds}) => {
    const a = new Date(seconds*1000);
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    const year = a.getFullYear();
    const month = months[a.getMonth()];
    const date = a.getDate();
    const time = date + ' ' + month + ' ' + year;

    return time;
}
```

to:

```js
export const convertDateFromTimestamp = ({seconds}) => {
    const date = new Date(seconds * 1000);
    const options = { year: 'numeric', month: 'short', day: 'numeric' };
    const time = event.toLocaleDateString(undefined, options);

    // and if you want to force a local
    // const time = event.toLocaleDateString('fr-FR', options);
    
    return time;
}
```

[Try it online](https://jsfiddle.net/qdoeg09f/)

[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString)

Cheers

**Comment by davide-ravasi** [comment]
Thanks for your feedback. :)

 It improves the quality of my code. Done it today :)

**Comment by aloisdg** [comment]
Glad to be useful :)
